### ISSUE TITLE
Missing `parallel_downloads`

### ISSUE THREAD

**Issue by fosskers** [Morganamilo/pacmanconf.rs#2]
`cargo build` works just fine on `master`, but `cargo test` fails with:
```
colin@yumi ~/c/r/pacmanconf.rs (master)> cargo test
   Compiling pacmanconf v0.1.2 (/home/colin/code/rust/pacmanconf.rs/pacmanconf)
error[E0063]: missing field `parallel_downloads` in initializer of `pacmanconf::Config`
   --> pacmanconf/src/pacmanconf.rs:280:27
    |
280 |         let pacman_conf = Config {
    |                           ^^^^^^ missing `parallel_downloads`

error: aborting due to previous error
```
Could this be because I don't have the `libalpm.so` installed that's based on Pacman's `master`?

**Comment by fosskers** [comment]
Hm my `rust-analyzer` doesn't like it either.

**Comment by Morganamilo** [comment]
Didn't realise the tests actually constructed a Config with all the fields so it broke the tests. Just an issue with the tests though, didn't effect pacmanconf actually running. Anyway Fixed now.

**Comment by fosskers** [comment]
Excellent, so I can bring this into Aura as a dependency.

**Comment by Morganamilo** [comment]
Well you could have either way, the actuall code was fine :p Plus cargo test doesn't run tests of dependencies.
